# -*- coding: utf-8 -*-
"""Di.gomez_parcial2_ingefin

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C-lh9ek-Thuaiy_qzJHai6FaVImPOGh6

# Liquefied petroleum gas (LPG) - Colombia
Sergio Cabrales, Universidad de los Andes

https://www.sac2.com/

## 1. Carga de librerías, funciones y APIs necesarias.

#### 1.1. Instalan las librerías que no incluye Google Colab
"""

pip install fredapi

pip install yfinance

pip install mplfinance

pip install arch

"""#### 1.2. Se cargan las librerías requeridas"""

# Funciones numéricas adicionales
import numpy as np

# Lectura de datos y manejo de Data-sets
import pandas as pd

# Datos
import yfinance as yfin

# Gráficos
import matplotlib.pyplot as plt
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
import statsmodels.api as sm
import seaborn as sns

#analisis tecnico
import mplfinance as mpf

# Probabilidad y estadística
import math
from scipy.stats import norm, chi2, jarque_bera,shapiro
from scipy.optimize import brentq
from scipy import stats

# ARCH model
from arch import arch_model

# Engel test for ARCH effects
from statsmodels.stats.diagnostic import het_arch

# FRED
from fredapi import Fred

# FRED_API_KEY
fred = Fred(api_key='a3d8a45391e92cc5c30c9c255819c138')

"""## 2. Obtención de datos históricos

#### 2.1. Descarga de datos desde la FRED

https://fred.stlouisfed.org/
"""

# Descargamos datos FRED para Propane Prices: Mont Belvieu, Texas
df_c = pd.DataFrame(fred.get_series('DPROPANEMBTX','2004-01-01'))
df_c = df_c.dropna()
df_c.index.names = ['Date']
df_c.columns = ["LPG"]
df_c

# Descargamos datos FRED para la gasolina regular
raw_df_trm = yfin.download('COP=X', start='2004-01-01', multi_level_index=False)
# Select the 'Close' column, drop NaNs, and convert to a DataFrame with a new column name.
# This makes sure we are operating on a single column from the start.
df_trm = pd.DataFrame(raw_df_trm['Close'].dropna())
df_trm.columns = ["TRM"]
df_trm.index.names = ['Date'] # Ensure index name is set after modifications

# Remove outliers where TRM is less than 1000
df_trm = df_trm[df_trm['TRM'] >= 1600]
df_trm

# Merge the DataFrames on the index
df = pd.merge(df_c, df_trm, on='Date')
df

kg_per_gal = 2.04
costo_gal = 200/1000

df['GLP'] = (costo_gal + (1/kg_per_gal)*np.array(df['LPG']).astype(float))*np.array(df['TRM']).astype(float)
df

"""# PUNTO 1

## 3. Visualización y Estadísticas Descriptivas

### 3.1. Grafica de precios
"""

#Plot adj close
plt.figure(figsize=(15,8))
plt.plot(df['LPG'], color = 'blue')
plt.title('LPG')
plt.xlabel('Fecha')
plt.ylabel('Precio ($)')
plt.show()



"""## 4. Retornos

### 4.1. Retornos Logarítmicos

Los retornos logarítmicos se calculan como:
$$
r_{t} = ln \left( \frac{S_t}{S_{t-1}} \right ) = ln \left( S_{t} \right) - ln \left( S_{t-1} \right)
$$
"""

# Guardamos los retornos logaritmicos en una nueva columna.
df['Log Returns LPG'] = np.log(df['LPG']) - np.log(df['LPG'].shift(1))
df['Log Returns LPG'][0] = 0
df

"""### 4.3. Retornos Logarítmicos anualizados

Podemos calcular el log-retorno anual ($r$) como el número de días bursátiles (252 días) por el promedio del log-retorno diario:

$$
r = 252 \bar{r_t}
$$
"""

# Podemos imprimir el retornos anual:
LogReturns = np.mean(df["Log Returns LPG"])*252
LogReturns

"""### 4.4. Gráfica de retornos
- Podemos graficar los retornos igual que como graficamos los precios.
"""

# Gráfico de los retornos logarítmicos
plt.figure(figsize=(15,8))
plt.plot(df['Log Returns LPG'], color = 'red')
plt.title('Retornos Logarítmicos')
plt.xlabel('Fecha')
plt.show()

"""## 10. GARCH model

### 10.1. GARCH model

$ \sigma_{t}^{2} = \alpha_{0} + \sum^{q}_{j=1} \alpha_j ϵ_{t-j}^{2} + \sum^{p}_{j=1} \beta_i \sigma_{t-j}^{2}  $
"""

# Create the GARCH model
#model = arch_model(df['Log Returns'], vol='GARCH', p=1, q=1, rescale=False)
model = arch_model(df['Log Returns LPG'], mean='Zero', vol='GARCH', p=1, q=1, rescale=False)
# Fit the model
results = model.fit()

# Print the results summary
print(results.summary())

params = pd.DataFrame(results.params)
params

# get residuals
e = pd.DataFrame(results.std_resid)
e['resid^2'] = e['std_resid']**2
e

"""## Resouesta 1.a

en tu modelo GARCH(1,1) los tres coeficientes (omega, alpha[1] y beta[1]) son estadísticamente significativos, ya que todos presentan p-values cercanos a 0 (menores a 0.05).
"""



# get residuals
e = pd.DataFrame(results.std_resid)
e['resid^2'] = e['std_resid']**2
e

"""### 10.2. Histogram of Residuals"""

# Create a histogram with k bins
k = int(math.sqrt(len(e['std_resid'])))

plt.hist(e['std_resid'], bins=k)

# Add labels and a title
plt.xlabel('Values')
plt.ylabel('Frequency')
plt.title('Histogram of Residuals')

# Show the plot
plt.show()

"""### 10.3. Q-Q plot - Residuals"""

# Se crea una Q-Q plot con el paquete statsmodels.api
pplot = sm.ProbPlot(e['std_resid'], stats.norm, fit=True)
# Se agrega un título a la gráfica
fig = pplot.qqplot(line="45")
plt.title("Q-Q Plot")
# Se muestra la gráfica
plt.show()

"""### 10.3. P-P plot - Residuals"""

# Se crea una P-PQ plot
pplot = sm.ProbPlot(e['std_resid'], stats.norm, fit=True)
# Se agrega un título a la gráfica
fig = pplot.ppplot(line="45")
plt.title("P-P Plot")
# Se muestra la gráfica
plt.show()

"""### 10.5. Autocorrelation - Residuals"""

# Crear el autocorrelograma
plot_acf(e['std_resid'], lags = 21)
plt.show()

# Crear el autocorrelograma
plot_acf(e['resid^2'], lags = 21)
plt.show()

"""### 10.6. Jarque-Bera of residuals"""

# perform the Jarque-Bera test
jb_value, p_value = jarque_bera(e['std_resid'])

# print the results
print("Jarque-Bera value: ", jb_value)
print("p-value: ", p_value)

if p_value > 0.05:
    print("The data is normally distributed")
else:
    print("The data is not normally distributed")

"""## Respuesta 1.b

Se rechaza la hipotesis de que los residuos sigan una distribución normal
"""



"""### 10.7. Box-Ljung test - Squared.Residuals"""

# Define the number of lags for the test (usually chosen based on data characteristics)
lags = 6
# perform the Ljung-Box test
lb_test = sm.stats.diagnostic.acorr_ljungbox(e['resid^2'], lags)

# print the results
print("Ljung-Box value: ", lb_test.iloc[-1, 0])
print("p-value: ", lb_test.iloc[-1, 1])

if lb_test.iloc[-1, 1] > 0.05:
    print("The data is independent")
else:
    print("The data is not independent")

"""## Respuesta 1.c

Los residuales al cuadrado no son independientes, ya que el test de Ljung-Box arroja un p-valor muy cercano a cero (0.00025 < 0.05), lo que indica la presencia de autocorrelación significativa. Esto sugiere que aún existe heterocedasticidad condicional en la serie, es decir, el modelo no ha capturado completamente la dinámica de la volatilidad.
"""



"""### 10.8. Volatility - Forecast"""

fig = results.plot(annualize="D")

df['Volatility'] = results.conditional_volatility*math.sqrt(12)
# Gráfico de la volatilidad
plt.figure(figsize=(15,8))
plt.plot(df['Volatility'], color = 'red')
plt.title('Volatility - GARCH')
plt.xlabel('Fecha')
plt.ylabel('Volatility')
plt.show()

print("El último valor de volatilidad es", round(df['Volatility'][-1]*100,4),"%")

vol_LPG = round(df['Volatility'][-1],4)
vol_LPG

"""#PUNTO 2"""



"""## 4. Retornos

### 4.1. Retornos Logarítmicos

Los retornos logarítmicos se calculan como:
$$
r_{t} = ln \left( \frac{S_t}{S_{t-1}} \right ) = ln \left( S_{t} \right) - ln \left( S_{t-1} \right)
$$
"""

# Guardamos los retornos logaritmicos en una nueva columna.
df['Log Returns TRM'] = np.log(df['TRM']) - np.log(df['TRM'].shift(1))
df['Log Returns TRM'][0] = 0
df

"""### 4.3. Retornos Logarítmicos anualizados

Podemos calcular el log-retorno anual ($r$) como el número de días bursátiles (252 días) por el promedio del log-retorno diario:

$$
r = 252 \bar{r_t}
$$
"""

# Podemos imprimir el retornos anual:
LogReturns = np.mean(df["Log Returns TRM"])*252
LogReturns

"""### 4.4. Gráfica de retornos
- Podemos graficar los retornos igual que como graficamos los precios.
"""

# Gráfico de los retornos logarítmicos
plt.figure(figsize=(15,8))
plt.plot(df['Log Returns TRM'], color = 'red')
plt.title('Retornos Logarítmicos')
plt.xlabel('Fecha')
plt.show()

"""## 10. GARCH model

### 10.1. GARCH model

$ \sigma_{t}^{2} = \alpha_{0} + \sum^{q}_{j=1} \alpha_j ϵ_{t-j}^{2} + \sum^{p}_{j=1} \beta_i \sigma_{t-j}^{2}  $
"""

# Create the GARCH model
#model = arch_model(df['Log Returns'], vol='GARCH', p=1, q=1, rescale=False)
model2 = arch_model(df['Log Returns TRM'], mean='Zero', vol='GARCH', p=1, q=1, rescale=False)
# Fit the model
results2 = model.fit()

# Print the results summary
print(results2.summary())

params2 = pd.DataFrame(results2.params)
params2

# get residuals
e = pd.DataFrame(results2.std_resid)
e['resid^2'] = e['std_resid']**2
e



"""### 10.8. Volatility - Forecast"""

fig = results2.plot(annualize="D")

df['Volatility TRM'] = results.conditional_volatility*math.sqrt(252)
# Gráfico de la volatilidad
plt.figure(figsize=(15,8))
plt.plot(df['Volatility TRM'], color = 'red')
plt.title('Volatility - GARCH')
plt.xlabel('Fecha')
plt.ylabel('Volatility')
plt.show()

print("El último valor de volatilidad es", round(df['Volatility TRM'][-1]*100,4),"%")

"""##2.a

todos los parámetros (omega, alpha[1] y beta[1]) son estadísticamente significativos
"""



# get residuals
e = pd.DataFrame(results2.std_resid)
e['resid^2'] = e['std_resid']**2
e

"""### 10.2. Histogram of Residuals"""

# Create a histogram with k bins
k = int(math.sqrt(len(e['std_resid'])))

plt.hist(e['std_resid'], bins=k)

# Add labels and a title
plt.xlabel('Values')
plt.ylabel('Frequency')
plt.title('Histogram of Residuals')

# Show the plot
plt.show()

"""### 10.3. Q-Q plot - Residuals"""

# Se crea una Q-Q plot con el paquete statsmodels.api
pplot = sm.ProbPlot(e['std_resid'], stats.norm, fit=True)
# Se agrega un título a la gráfica
fig = pplot.qqplot(line="45")
plt.title("Q-Q Plot")
# Se muestra la gráfica
plt.show()

"""### 10.3. P-P plot - Residuals"""

# Se crea una P-PQ plot
pplot = sm.ProbPlot(e['std_resid'], stats.norm, fit=True)
# Se agrega un título a la gráfica
fig = pplot.ppplot(line="45")
plt.title("P-P Plot")
# Se muestra la gráfica
plt.show()

"""### 10.5. Autocorrelation - Residuals"""

# Crear el autocorrelograma
plot_acf(e['std_resid'], lags = 21)
plt.show()

# Crear el autocorrelograma
plot_acf(e['resid^2'], lags = 21)
plt.show()

"""### 10.6. Jarque-Bera of residuals"""

# perform the Jarque-Bera test
jb_value, p_value = jarque_bera(e['std_resid'])

# print the results
print("Jarque-Bera value: ", jb_value)
print("p-value: ", p_value)

if p_value > 0.05:
    print("The data is normally distributed")
else:
    print("The data is not normally distributed")

"""2.b

no se distribuye normal
"""



"""### 10.7. Box-Ljung test - Squared.Residuals"""

# Define the number of lags for the test (usually chosen based on data characteristics)
lags = 6
# perform the Ljung-Box test
lb_test = sm.stats.diagnostic.acorr_ljungbox(e['resid^2'], lags)

# print the results
print("Ljung-Box value: ", lb_test.iloc[-1, 0])
print("p-value: ", lb_test.iloc[-1, 1])

if lb_test.iloc[-1, 1] > 0.05:
    print("The data is independent")
else:
    print("The data is not independent")

"""##2.c

los datos no son independientes
"""



"""### 10.8. Volatility - Forecast"""

fig = results2.plot(annualize="D")

df['VolatilityTRM'] = results.conditional_volatility*math.sqrt(12)
# Gráfico de la volatilidad
plt.figure(figsize=(15,8))
plt.plot(df['VolatilityTRM'], color = 'red')
plt.title('Volatility TRM - GARCH')
plt.xlabel('Fecha')
plt.ylabel('VolatilityTRM')
plt.show()

print("El último valor de volatilidad es", round(df['VolatilityTRM'][-1]*100,4),"%")

"""#PUNTO 3"""

df

"""## Augmented Dickey–Fuller test (ADF)"""

from statsmodels.tsa.stattools import adfuller

# test for stationarity using the ADF test
result = adfuller(df['LPG'])
print("ADF statistic: ", result[0])
print("p-value: ", result[1])
print("Critical values: ", result[4])

# print the results
if result[1] < 0.05:
    print("The series is stationary")
else:
    print("The series is not stationary")

"""## Mean Reversion Model"""

y = df['LPG'] - df['LPG'].shift(1)
y

X = sm.add_constant(df['LPG'].shift(1))
X

# Define the mean reversion model
model = sm.OLS(y, X, missing='drop')

# Fit the model
result = model.fit()

# Print the summary of the regression results
print(result.summary())

a = result.params[0]
a

b = result.params[1]
b

#obtain standardized residuals
residuals = result.resid
sigma_e = np.std(result.resid)
sigma_e

# Long-term mean
m = -a/b
m

# Speed of mean reversion
eta = -np.log(1+b)
eta

vol_LPG

# Parameters
m = m      # Long-term mean
sigma =  vol_LPG    # Volatility
eta = eta   # Speed of mean reversion
N = 252
dt = 1/N    # Time step
T = 13/12        # Time horizon
n = 10000      # Number of simulations
S0 = df['TRM'][-1]       # Initial price
S0

# Function to simulate paths
def simulate_path(m, sigma, eta, dt, T, n, S0, sigma_e):
    timesteps = int(T/dt)
    paths = np.zeros((n, timesteps+1))
    paths[:,0] = S0

    for i in range(n):
        for j in range(1, timesteps+1):
          paths[i,j] = m*(1-np.exp(-eta))+ np.exp(-eta)*paths[i,j-1] + np.random.normal(loc=0,scale=sigma_e)

    return paths

# Simulate paths
paths = simulate_path(m, sigma, eta, dt, T, n, S0, sigma_e)

mean_last_value_cambio = np.mean(paths[:, -1])
print(mean_last_value_cambio)

# Extraer el precio final de cada trayectoria (S_T)
ST = paths[:, -1]

# Calcular el percentil 95%
percentil_5 = np.percentile(ST, 5)

print(f"Percentil 5% del precio simulado en T: {percentil_5}")

"""#PUNTO 4"""



"""### Geometric Brownian Motion (GBM) - 1 path"""

# Define the parameters of the stochastic process
T = 13/12       # Time horizon
N = 252      # Number of time steps
dt = T / N    # Time step size
mu = df['Volatility'].mean()    # Mean of the process
sigma = vol_LPG   # Volatility of the process

# Define the initial condition
S0 = df["LPG"][-1]

"""### Geometric Brownian Motion (GBM) - R paths"""

def gbm_paths(S0, mu, sigma, T, N, num_paths):
    dt = T/N
    paths = np.zeros((num_paths, N+1))
    paths[:, 0] = S0

    for i in range(num_paths):
        for j in range(1, N+1):
            drift = (mu - 0.5 * sigma**2) * dt
            diffusion = sigma * np.sqrt(dt) * np.random.normal()
            paths[i, j] = paths[i, j-1] * np.exp(drift + diffusion)

    return paths

num_paths = 10000

paths = gbm_paths(S0, mu, vol, T, N, num_paths)

plt.figure(figsize=(10, 6))
plt.plot(paths.T)
plt.xlabel('Time Steps')
plt.ylabel('Stock Price')
plt.title('Geometric Brownian Motion')
plt.show()

mean_last_value_cambio = np.mean(paths[:, -1])
print(mean_last_value_cambio)

# Extraer el precio final de cada trayectoria (S_T)
ST = paths[:, -1]

# Calcular el percentil 95%
percentil_5 = np.percentile(ST, 5)

print(f"Percentil 5% del precio simulado en T: {percentil_5}")

"""##PUNTO 5"""

df

"""## Augmented Dickey–Fuller test (ADF)"""

from statsmodels.tsa.stattools import adfuller

# test for stationarity using the ADF test
result = adfuller(df['LPG'])
print("ADF statistic: ", result[0])
print("p-value: ", result[1])
print("Critical values: ", result[4])

# print the results
if result[1] < 0.05:
    print("The series is stationary")
else:
    print("The series is not stationary")

"""## Mean Reversion Model"""

y = df['LPG'] - df['LPG'].shift(1)
y

X = sm.add_constant(df['LPG'].shift(1))
X

# Define the mean reversion model
model = sm.OLS(y, X, missing='drop')

# Fit the model
result = model.fit()

# Print the summary of the regression results
print(result.summary())

a = result.params[0]
a

b = result.params[1]
b

#obtain standardized residuals
residuals = result.resid
sigma_e = np.std(result.resid)
sigma_e

# Long-term mean
m = -a/b
m

# Speed of mean reversion
eta = -np.log(1+b)
eta

vol_LPG

# Parameters
m = m      # Long-term mean
sigma =  vol_LPG    # Volatility
eta = eta   # Speed of mean reversion
N = 252
dt = 1/N    # Time step
T = 13/12        # Time horizon
n = 10000      # Number of simulations
S0 = df['TRM'][-1]       # Initial price
S0

# Function to simulate paths
def simulate_path(m, sigma, eta, dt, T, n, S0, sigma_e):
    timesteps = int(T/dt)
    paths = np.zeros((n, timesteps+1))
    paths[:,0] = S0

    for i in range(n):
        for j in range(1, timesteps+1):
          paths[i,j] = m*(1-np.exp(-eta))+ np.exp(-eta)*paths[i,j-1] + np.random.normal(loc=0,scale=sigma_e)

    return paths

# Simulate paths
paths = simulate_path(m, sigma, eta, dt, T, n, S0, sigma_e)

mean_last_value_cambio = np.mean(paths[:, -1])
print(mean_last_value_cambio)